version: "3.3"

services:
  bot:
    build: TreinpositiesBot
    environment:
      Core__DiscordToken: # Bot token
      Core__AdminBackendUrl: backend
  backend:
    build: WebAdmin.Backend
    environment:
      Database: Host=database; Database=app-data; Port=5432; Username=app; Password=test123
  database:
    image: "postgres:13.3"
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: app-data
    ports:
      - "5432:5432"
    volumes:
      - database-data:/var/lib/postgresql/data/
      
volumes:
  database-data:
