version: "3.3"

services:
  bot:
    build:
      context: .
      dockerfile: TreinpositiesBot/Dockerfile
    env_file:
      - bot.env
    environment:
      Core__AdminBackendUrl: http://backend
  backend:
    build:
      context: .
      dockerfile: WebAdmin.Backend/Dockerfile
    env_file:
      - bot.env
    environment:
      Redis__Endpoints__0: redis:6379
      ASPNETCORE_ENVIRONMENT: Development
      AllowedCorsOrigins__0: "http://localhost:4200"
    ports:
      - "8180:80"
  redis:
    image: "redis:7-alpine"
    command: --save 60 1 --loglevel warning
    volumes:
      - redis-data:/data:rw
    ports:
      - "6379:6379"
  frontend:
    build:
      context: WebAdmin.Frontend
      dockerfile: WebAdmin.Frontend/docker/Dockerfile
    ports:
      - "8080:80"
      
volumes:
  redis-data:
