version: "3.3"

services:
  bot:
    build:
      context: .
      dockerfile: TreinpositiesBot/Dockerfile
    env_file:
      - bot.env
    environment:
      Core__AdminBackendUrl: http://backend
  backend:
    build:
      context: .
      dockerfile: WebAdmin.Backend/Dockerfile
    environment:
      Database: Host=database; Database=app-data; Port=5432; Username=app; Password=app
      ASPNETCORE_ENVIRONMENT: Development
    ports:
      - "8180:80"
  database:
    image: "postgres:13.3"
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: app-data
    ports:
      - "5432:5432"
    volumes:
      - database-data:/var/lib/postgresql/data/
  frontend:
    build:
      context: WebAdmin.Frontend
      dockerfile: WebAdmin.Frontend/docker/Dockerfile
    ports:
      - "8080:80"
      
volumes:
  database-data:
